[tox]
envlist = py36, py37, py38, py39, flake8

[travis]
python =
    3.9: py39
    3.8: py38
    3.7: py37
    3.6: py36

[testenv:flake8]
basepython = python
deps = flake8
commands = flake8 {{ cookiecutter.project_slug }} tests

[testenv]
setenv =
    PYTHONPATH = {toxinidir}
    PYTEST_ADDOPTS = --ignore-glob=*integration*
{% if cookiecutter.use_pytest == 'y' -%}
deps =
    -r{toxinidir}/requirements-dev.txt
; If you want to make tox run the tests with the same versions, create a
; requirements.txt with the pinned versions and uncomment the following line:
;     -r{toxinidir}/requirements.txt
commands =
    pip install -U pip
    pytest --basetemp={envtmpdir}
{% else %}
commands = python setup.py test
{%- endif %}

[flake8]
ignore =
    # F403: star import used
    F403
    # F405: variable may be undefined, or defined from star imports
    F405
